"""Domain and configuration models."""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field


class Severity(StrEnum):
    """Violation severity."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class Violation(BaseModel):
    """One audit finding."""

    rule_id: str
    severity: Severity
    message: str
    path: str = "."
    suggestion: str | None = None
    auto_fixable: bool = False


class AuditReport(BaseModel):
    """Serializable scan result."""

    root: str
    violations: list[Violation] = Field(default_factory=list)

    @property
    def has_errors(self) -> bool:
        return any(item.severity is Severity.ERROR for item in self.violations)


class RuleSettings(BaseModel):
    """Per-rule switches."""

    model_config = ConfigDict(extra="forbid")

    enabled: bool = True
    severity: Severity | None = None


class ScanSettings(BaseModel):
    """Limits used while walking a repository."""

    model_config = ConfigDict(extra="forbid")

    max_file_size: int = Field(default=1_048_576, gt=0)
    exclude: list[str] = Field(default_factory=lambda: [".git", ".venv", "node_modules"])


class TemplateSettings(BaseModel):
    """Values passed to built-in Jinja templates."""

    model_config = ConfigDict(extra="forbid")

    project_name: str | None = None
    license_holder: str = "ТРЕБУЕТ УТОЧНЕНИЯ"
    python_package: str = "project"


class RepoDoctorConfig(BaseModel):
    """Top-level YAML/JSON configuration."""

    model_config = ConfigDict(extra="forbid")

    version: int = Field(default=1, ge=1, le=1)
    rules: dict[str, RuleSettings] = Field(default_factory=dict)
    scan: ScanSettings = Field(default_factory=ScanSettings)
    templates: TemplateSettings = Field(default_factory=TemplateSettings)


class FixAction(BaseModel):
    """Planned or completed file generation."""

    path: str
    status: str
    reason: str


class PullRequestRequest(BaseModel):
    """Provider-neutral change request."""

    owner: str
    repository: str
    source_branch: str
    target_branch: str = "main"
    title: str = "chore: apply Repo Doctor fixes"
    body: str = "Automated repository standardization generated by Repo Doctor."


def relative_display(path: Path, root: Path) -> str:
    """Return a stable POSIX path relative to the audited root."""

    try:
        value = path.relative_to(root)
    except ValueError:
        return "."
    return value.as_posix() or "."
